/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendaTelefonica;

import java.io.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * @author Raul Martin Perez
 */
public class Interfaz extends javax.swing.JFrame {
    ArrayList<Contacto> contactos = new ArrayList<>();

    /*
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        jPanelAgenda.setVisible(false);
        jPanelMostrar.setVisible(false);
        jPanelAnaidir.setVisible(false);
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicio = new javax.swing.JPanel();
        jButtonAgenda = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jPanelAgenda = new javax.swing.JPanel();
        jLabelBuscar = new javax.swing.JLabel();
        jComboBoxOpciones = new javax.swing.JComboBox<>();
        jTextFieldVariable = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jLabelLista = new javax.swing.JLabel();
        jScrollPaneContactos = new javax.swing.JScrollPane();
        jListContactos = new javax.swing.JList<>();
        jButtonInfo = new javax.swing.JButton();
        jButtonAnaidir = new javax.swing.JButton();
        jPanelMostrar = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jLabelDatos = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelTelefonos = new javax.swing.JLabel();
        jScrollPaneTelefonos = new javax.swing.JScrollPane();
        jTextAreaTelefonos = new javax.swing.JTextArea();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jPanelAnaidir = new javax.swing.JPanel();
        jButtonHome1 = new javax.swing.JButton();
        jLabelDatos1 = new javax.swing.JLabel();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelTelefonos1 = new javax.swing.JLabel();
        jScrollPaneTelefonos1 = new javax.swing.JScrollPane();
        jTextAreaTelefonos1 = new javax.swing.JTextArea();
        jButtonAceptar = new javax.swing.JButton();
        jMenuBarAgenda = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemVaciar = new javax.swing.JMenuItem();
        jMenuItemExportar = new javax.swing.JMenuItem();
        jMenuItemImportar = new javax.swing.JMenuItem();
        jMenuItemCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda URJC");
        setIconImage(new ImageIcon(getClass().getResource("/agendaTelefonica/Agenda.png")).getImage());
        setResizable(false);

        jPanelInicio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInicio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jButtonAgenda.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonAgenda.setText("Agenda");
        jButtonAgenda.setToolTipText("Inicia la aplicación");
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });

        jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Logo_URJC.png"))); // NOI18N

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Fondo_Agenda.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jButtonAgenda)
                .addGap(234, 234, 234))
            .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(jLabelLogo)
                    .addGap(160, 160, 160)))
            .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInicioLayout.createSequentialGroup()
                    .addComponent(jLabelFondo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jButtonAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jLabelLogo)
                    .addGap(79, 79, 79)))
            .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInicioLayout.createSequentialGroup()
                    .addComponent(jLabelFondo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelAgenda.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAgenda.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabelBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabelBuscar.setText("Buscar por:");

        jComboBoxOpciones.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jComboBoxOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Teléfono" }));
        jComboBoxOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpcionesActionPerformed(evt);
            }
        });

        jTextFieldVariable.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jTextFieldVariable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Buscar_Usuario.png"))); // NOI18N
        jButtonBuscar.setToolTipText("Busca a un usuario con los datos pasados");
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(57, 57));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonBorrar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Borrar.png"))); // NOI18N
        jButtonBorrar.setToolTipText("Borra la busqueda realizada");
        jButtonBorrar.setPreferredSize(new java.awt.Dimension(57, 57));
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jLabelLista.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLista.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabelLista.setText("<HTML><U>Lista de contactos:</U></HTML>");

        jScrollPaneContactos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jListContactos.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jListContactos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Contacto 1", "Contacto 2", "Contacto 3", "Contacto 4", "Contacto 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListContactos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneContactos.setViewportView(jListContactos);

        jButtonInfo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Info_Usuario.png"))); // NOI18N
        jButtonInfo.setToolTipText("Muestra los datos del contacto seleccionado");
        jButtonInfo.setPreferredSize(new java.awt.Dimension(57, 57));
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });

        jButtonAnaidir.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonAnaidir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Nuevo_Usuario.png"))); // NOI18N
        jButtonAnaidir.setToolTipText("Añade un nuevo usuario");
        jButtonAnaidir.setPreferredSize(new java.awt.Dimension(57, 57));
        jButtonAnaidir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnaidirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgendaLayout = new javax.swing.GroupLayout(jPanelAgenda);
        jPanelAgenda.setLayout(jPanelAgendaLayout);
        jPanelAgendaLayout.setHorizontalGroup(
            jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAgendaLayout.createSequentialGroup()
                        .addComponent(jScrollPaneContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAgendaLayout.createSequentialGroup()
                        .addComponent(jLabelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgendaLayout.createSequentialGroup()
                        .addGroup(jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAgendaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jButtonAnaidir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAgendaLayout.createSequentialGroup()
                                .addComponent(jLabelBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jTextFieldVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        jPanelAgendaLayout.setVerticalGroup(
            jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jLabelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPaneContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanelAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAnaidir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelMostrar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMostrar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jButtonHome.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Home.png"))); // NOI18N
        jButtonHome.setToolTipText("Volver a la pantalla principal");
        jButtonHome.setPreferredSize(new java.awt.Dimension(57, 57));
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jLabelDatos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDatos.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabelDatos.setText("<HTML><U>Datos del contacto:</U></HTML>");

        jLabelNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jTextFieldNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTelefonos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTelefonos.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabelTelefonos.setText("Teléfonos:");

        jScrollPaneTelefonos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextAreaTelefonos.setColumns(20);
        jTextAreaTelefonos.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jTextAreaTelefonos.setRows(5);
        jScrollPaneTelefonos.setViewportView(jTextAreaTelefonos);

        jButtonEditar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Editar_Usuario.png"))); // NOI18N
        jButtonEditar.setToolTipText("Edita el contacto");
        jButtonEditar.setPreferredSize(new java.awt.Dimension(57, 57));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Borrar_Usuario.png"))); // NOI18N
        jButtonEliminar.setToolTipText("Elimina el contacto");
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(57, 57));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMostrarLayout = new javax.swing.GroupLayout(jPanelMostrar);
        jPanelMostrar.setLayout(jPanelMostrarLayout);
        jPanelMostrarLayout.setHorizontalGroup(
            jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTelefonos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMostrarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMostrarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelMostrarLayout.createSequentialGroup()
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNombre)
                            .addComponent(jScrollPaneTelefonos, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanelMostrarLayout.setVerticalGroup(
            jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addGap(15, 15, 15)
                .addGroup(jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTelefonos)
                    .addComponent(jScrollPaneTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanelAnaidir.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAnaidir.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jButtonHome1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Home.png"))); // NOI18N
        jButtonHome1.setToolTipText("Volver a la pantalla principal");
        jButtonHome1.setPreferredSize(new java.awt.Dimension(57, 57));
        jButtonHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHome1ActionPerformed(evt);
            }
        });

        jLabelDatos1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDatos1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabelDatos1.setText("<HTML><U>Introduzca los datos del nuevo contacto:</U></HTML>");

        jTextFieldNombre1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jTextFieldNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNombre1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabelNombre1.setText("Nombre:");

        jLabelTelefonos1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTelefonos1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabelTelefonos1.setText("Teléfonos:");

        jScrollPaneTelefonos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextAreaTelefonos1.setColumns(20);
        jTextAreaTelefonos1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jTextAreaTelefonos1.setRows(5);
        jScrollPaneTelefonos1.setViewportView(jTextAreaTelefonos1);

        jButtonAceptar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Aceptar_Usuario.png"))); // NOI18N
        jButtonAceptar.setToolTipText("Guarda el nuevo contscto");
        jButtonAceptar.setPreferredSize(new java.awt.Dimension(57, 57));
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAnaidirLayout = new javax.swing.GroupLayout(jPanelAnaidir);
        jPanelAnaidir.setLayout(jPanelAnaidirLayout);
        jPanelAnaidirLayout.setHorizontalGroup(
            jPanelAnaidirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnaidirLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanelAnaidirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTelefonos1)
                    .addComponent(jButtonHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelAnaidirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAnaidirLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAnaidirLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAnaidirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelAnaidirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNombre1)
                                .addComponent(jScrollPaneTelefonos1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanelAnaidirLayout.setVerticalGroup(
            jPanelAnaidirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnaidirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAnaidirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAnaidirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre1))
                .addGap(15, 15, 15)
                .addGroup(jPanelAnaidirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTelefonos1)
                    .addComponent(jScrollPaneTelefonos1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenuArchivo.setBackground(new java.awt.Color(255, 255, 255));
        jMenuArchivo.setText("Archivo");
        jMenuArchivo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jMenuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGuardar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jMenuItemGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Guardar.png"))); // NOI18N
        jMenuItemGuardar.setText("Guardar Agenda");
        jMenuItemGuardar.setToolTipText("Guarda todos los contactos de la agenda");
        jMenuItemGuardar.setPreferredSize(new java.awt.Dimension(250, 60));
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuardar);

        jMenuItemVaciar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVaciar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jMenuItemVaciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Eliminar.png"))); // NOI18N
        jMenuItemVaciar.setText("Vaciar Agenda");
        jMenuItemVaciar.setToolTipText("Elimina todos los contactos de la agenda");
        jMenuItemVaciar.setPreferredSize(new java.awt.Dimension(250, 60));
        jMenuItemVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVaciarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemVaciar);

        jMenuItemExportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemExportar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jMenuItemExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Exportar.png"))); // NOI18N
        jMenuItemExportar.setText("Exportar Agenda");
        jMenuItemExportar.setToolTipText("Exporta todos los contactos a un archivo");
        jMenuItemExportar.setPreferredSize(new java.awt.Dimension(250, 60));
        jMenuItemExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExportarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemExportar);

        jMenuItemImportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemImportar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jMenuItemImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Importar.png"))); // NOI18N
        jMenuItemImportar.setText("Importar Agenda");
        jMenuItemImportar.setToolTipText("Importa todos los contactos de un archivo");
        jMenuItemImportar.setPreferredSize(new java.awt.Dimension(250, 60));
        jMenuItemImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemImportar);

        jMenuItemCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCerrar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jMenuItemCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agendaTelefonica/Cerrar_Ventana.png"))); // NOI18N
        jMenuItemCerrar.setText("Cerrar Agenda");
        jMenuItemCerrar.setToolTipText("Cierra la agenda");
        jMenuItemCerrar.setPreferredSize(new java.awt.Dimension(250, 60));
        jMenuItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemCerrar);

        jMenuBarAgenda.add(jMenuArchivo);

        setJMenuBar(jMenuBarAgenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelAnaidir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelAnaidir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVaciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVaciarActionPerformed

    private void jMenuItemExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExportarActionPerformed
        contactos = null;
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos CSV", "csv");
        ImageIcon icon = new ImageIcon(getClass().getResource("/agendaTelefonica/CSV.png"));
        JFileChooser chooser = new JFileChooser();
        chooser.setApproveButtonText("Guardar");
        chooser.setApproveButtonToolTipText("Guarda el archivo seleccionado");
        chooser.setDialogTitle("Exportar");
        chooser.setFileFilter(filter);
        chooser.setSelectedFile(new File(".csv"));
        chooser.setToolTipText("Archivo.csv");
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String nombre;
            String ruta;
            if(chooser.getSelectedFile().getAbsolutePath().endsWith(".csv")) {
                nombre = chooser.getSelectedFile().getName();
                ruta = chooser.getSelectedFile().getPath();
            }
            else {
                nombre = chooser.getSelectedFile().getName() + ".csv";
                ruta = chooser.getSelectedFile().getPath() + ".csv";
            }
            try (FileOutputStream f = new FileOutputStream(ruta)) {
                ObjectOutputStream so= new ObjectOutputStream(f);
                so.writeObject(contactos);
                f.close();
                JOptionPane.showMessageDialog(this, "Exportado con éxito de " + nombre, "Exportar Agenda", JOptionPane.INFORMATION_MESSAGE, icon);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al exportar al fichero", "Exportar Agenda", JOptionPane.ERROR_MESSAGE, icon);
            }
        }
    }//GEN-LAST:event_jMenuItemExportarActionPerformed

    private void jMenuItemImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportarActionPerformed
        contactos = null;
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos CSV", "csv");
        ImageIcon icon = new ImageIcon(getClass().getResource("/agendaTelefonica/CSV.png"));
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Importar");
        chooser.setFileFilter(filter);
        chooser.setSelectedFile(new File(".csv"));
        chooser.setToolTipText("Archivo.csv");
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String nombre = chooser.getSelectedFile().getName();
            if(nombre.endsWith(".csv")) {
                String ruta = chooser.getSelectedFile().getPath();
                try { FileInputStream in = new FileInputStream(ruta);
                    ObjectInputStream ob = new ObjectInputStream(in);
                    contactos = (ArrayList<Contacto>) ob.readObject();
                    JOptionPane.showMessageDialog(this, "Importado con éxito de " + nombre, "Importar Agenda", JOptionPane.INFORMATION_MESSAGE, icon);
                }
                catch (IOException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "Error al importar del fichero", "Importar Agenda", JOptionPane.ERROR_MESSAGE, icon);
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "Solo se pueden leer archivos .csv", "Importar Agenda", JOptionPane.WARNING_MESSAGE, icon);
            }
        }
    }//GEN-LAST:event_jMenuItemImportarActionPerformed

    private void jMenuItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/agendaTelefonica/Salir.png"));
        int result = JOptionPane.showConfirmDialog(this, "¿Está seguro de que no desea guardar antes de salir?", "Cerrar Agenda", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (JOptionPane.OK_OPTION == result)
            System.exit(0);
    }//GEN-LAST:event_jMenuItemCerrarActionPerformed

    private void jComboBoxOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOpcionesActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/agendaTelefonica/Encontrar_Usuario.png"));
        JOptionPane.showMessageDialog(this, "¡Contacto no encontrado!", "Buscar Contacto", JOptionPane.WARNING_MESSAGE, icon);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonAnaidirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnaidirActionPerformed
        jPanelAgenda.setVisible(false);
        jPanelAnaidir.setVisible(true);
    }//GEN-LAST:event_jButtonAnaidirActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        jPanelInicio.setVisible(false);
        jPanelAgenda.setVisible(true);
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        jTextFieldNombre.setText("");
        jTextAreaTelefonos.setText("");
        jPanelMostrar.setVisible(false);
        jPanelAgenda.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/agendaTelefonica/Eliminar_Usuario.png"));
        int result = JOptionPane.showConfirmDialog(this, "¿Está seguro de que quiere eliminar este contacto?", "Eliminar Contacto", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (JOptionPane.OK_OPTION == result)
            JOptionPane.showMessageDialog(this, "¡Contacto eliminado con éxito!", "Eliminar Contacto", JOptionPane.INFORMATION_MESSAGE, icon);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHome1ActionPerformed
        jTextFieldNombre1.setText("");
        jTextAreaTelefonos1.setText("");
        jPanelAnaidir.setVisible(false);
        jPanelAgenda.setVisible(true);
    }//GEN-LAST:event_jButtonHome1ActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/agendaTelefonica/Añadir_Usuario.png"));
        JOptionPane.showMessageDialog(this, "¡Contacto ya existente!", "Añadir Contacto", JOptionPane.WARNING_MESSAGE, icon);
        JOptionPane.showMessageDialog(this, "¡Contacto añadido con éxito!", "Añadir Contacto", JOptionPane.INFORMATION_MESSAGE, icon);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/agendaTelefonica/Usuario.png"));
        if (jListContactos.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "¡Ningún contacto seleccionado!", "Ver Contacto", JOptionPane.ERROR_MESSAGE, icon);
        } else {
            jTextFieldVariable.setText("");
            jListContactos.clearSelection();
            jPanelAgenda.setVisible(false);
            jPanelMostrar.setVisible(true);
        }
    }//GEN-LAST:event_jButtonInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonAnaidir;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonHome1;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JComboBox<String> jComboBoxOpciones;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelDatos;
    private javax.swing.JLabel jLabelDatos1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLista;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelTelefonos;
    private javax.swing.JLabel jLabelTelefonos1;
    private javax.swing.JList<String> jListContactos;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBarAgenda;
    private javax.swing.JMenuItem jMenuItemCerrar;
    private javax.swing.JMenuItem jMenuItemExportar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemImportar;
    private javax.swing.JMenuItem jMenuItemVaciar;
    private javax.swing.JPanel jPanelAgenda;
    private javax.swing.JPanel jPanelAnaidir;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelMostrar;
    private javax.swing.JScrollPane jScrollPaneContactos;
    private javax.swing.JScrollPane jScrollPaneTelefonos;
    private javax.swing.JScrollPane jScrollPaneTelefonos1;
    private javax.swing.JTextArea jTextAreaTelefonos;
    private javax.swing.JTextArea jTextAreaTelefonos1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldVariable;
    // End of variables declaration//GEN-END:variables
}
